// Auto-generated by Supabase MCP `generate_typescript_types`. Regenerate
// via the same tool after every applied migration.
// Local patches (re-apply after every regeneration; grep this file for
// `PATCH:` to find them):
//   - PATCH: typegen renders DEFAULT NULL plpgsql args as plain `string`.
//     Nullable args on patient_create / patient_update / appointment_create /
//     appointment_update are marked `string | null` (or `boolean | null`) so
//     callers can pass null for "no change" / "unknown".
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      appointments: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          kind: string
          notes: string | null
          patient_id: string
          room_id: string
          slot_end_at: string
          slot_start_at: string
          status: string
          subtype: string | null
          tenant_id: string
          updated_at: string
          with_contrast: boolean
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          kind: string
          notes?: string | null
          patient_id: string
          room_id: string
          slot_end_at: string
          slot_start_at: string
          status?: string
          subtype?: string | null
          tenant_id: string
          updated_at?: string
          with_contrast?: boolean
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          kind?: string
          notes?: string | null
          patient_id?: string
          room_id?: string
          slot_end_at?: string
          slot_start_at?: string
          status?: string
          subtype?: string | null
          tenant_id?: string
          updated_at?: string
          with_contrast?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "appointments_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_events: {
        Row: {
          actor: Json
          chain_sequence: number
          consent_state_snapshot: Json | null
          content_hash: string
          context: Json | null
          event_id: string
          event_type: string
          finalita: string
          model_provenance: Json | null
          prev_hash: string | null
          scope_snapshot: Json | null
          source_subsystem: string
          subject: string
          tenant_id: string
          timestamp_utc: string
        }
        Insert: {
          actor: Json
          chain_sequence?: number
          consent_state_snapshot?: Json | null
          content_hash: string
          context?: Json | null
          event_id?: string
          event_type: string
          finalita: string
          model_provenance?: Json | null
          prev_hash?: string | null
          scope_snapshot?: Json | null
          source_subsystem: string
          subject: string
          tenant_id: string
          timestamp_utc?: string
        }
        Update: {
          actor?: Json
          chain_sequence?: number
          consent_state_snapshot?: Json | null
          content_hash?: string
          context?: Json | null
          event_id?: string
          event_type?: string
          finalita?: string
          model_provenance?: Json | null
          prev_hash?: string | null
          scope_snapshot?: Json | null
          source_subsystem?: string
          subject?: string
          tenant_id?: string
          timestamp_utc?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      clinician_profiles: {
        Row: {
          albo: string | null
          break_glass_active: boolean
          break_glass_expires_at: string | null
          codice_fiscale: string | null
          consent_version: number
          created_at: string
          current_assignment: Json | null
          fnomceo_iscrizione: string | null
          id: string
          scope_version: number
          specializzazione: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          albo?: string | null
          break_glass_active?: boolean
          break_glass_expires_at?: string | null
          codice_fiscale?: string | null
          consent_version?: number
          created_at?: string
          current_assignment?: Json | null
          fnomceo_iscrizione?: string | null
          id: string
          scope_version?: number
          specializzazione?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          albo?: string | null
          break_glass_active?: boolean
          break_glass_expires_at?: string | null
          codice_fiscale?: string | null
          consent_version?: number
          created_at?: string
          current_assignment?: Json | null
          fnomceo_iscrizione?: string | null
          id?: string
          scope_version?: number
          specializzazione?: string | null
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "clinician_profiles_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      egfr_results: {
        Row: {
          created_at: string
          id: string
          patient_id: string
          taken_at: string
          tenant_id: string
          value: number
        }
        Insert: {
          created_at?: string
          id?: string
          patient_id: string
          taken_at?: string
          tenant_id: string
          value: number
        }
        Update: {
          created_at?: string
          id?: string
          patient_id?: string
          taken_at?: string
          tenant_id?: string
          value?: number
        }
        Relationships: [
          {
            foreignKeyName: "egfr_results_patient_id_fkey"
            columns: ["patient_id"]
            isOneToOne: false
            referencedRelation: "patients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "egfr_results_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      event_queue: {
        Row: {
          cloudevent: Json
          created_at: string
          id: string
          processed_at: string | null
          tenant_id: string
        }
        Insert: {
          cloudevent: Json
          created_at?: string
          id: string
          processed_at?: string | null
          tenant_id: string
        }
        Update: {
          cloudevent?: Json
          created_at?: string
          id?: string
          processed_at?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "event_queue_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      patients: {
        Row: {
          codice_fiscale: string | null
          created_at: string
          created_by: string | null
          date_of_birth: string | null
          deleted_at: string | null
          family_name: string
          given_name: string
          id: string
          sex: string | null
          tenant_id: string
          updated_at: string
        }
        Insert: {
          codice_fiscale?: string | null
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          deleted_at?: string | null
          family_name: string
          given_name: string
          id?: string
          sex?: string | null
          tenant_id: string
          updated_at?: string
        }
        Update: {
          codice_fiscale?: string | null
          created_at?: string
          created_by?: string | null
          date_of_birth?: string | null
          deleted_at?: string | null
          family_name?: string
          given_name?: string
          id?: string
          sex?: string | null
          tenant_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "patients_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          created_at: string
          id: string
          name: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      appointment_cancel: {
        Args: {
          p_appointment_id: string
          p_cloudevent: Json
          p_cloudevent_id: string
          p_finalita: string
        }
        Returns: Json
      }
      appointment_create: {
        Args: {
          p_appointment_id: string
          p_cloudevent: Json
          p_cloudevent_id: string
          p_finalita: string
          p_kind: string
          p_notes: string | null // PATCH: nullable in SQL
          p_patient_id: string
          p_room_id: string
          p_slot_end_at: string
          p_slot_start_at: string
          p_subtype: string | null // PATCH: nullable in SQL
          p_with_contrast: boolean
        }
        Returns: Json
      }
      appointment_update: {
        Args: {
          p_appointment_id: string
          p_cloudevent: Json
          p_cloudevent_id: string
          p_finalita: string
          p_notes: string | null // PATCH: nullable in SQL (no-change)
          p_slot_end_at: string | null // PATCH: nullable in SQL (no-change)
          p_slot_start_at: string | null // PATCH: nullable in SQL (no-change)
          p_subtype: string | null // PATCH: nullable in SQL (no-change)
          p_with_contrast: boolean | null // PATCH: nullable in SQL (no-change)
        }
        Returns: Json
      }
      current_tenant_id: { Args: never; Returns: string }
      custom_access_token_hook: { Args: { event: Json }; Returns: Json }
      patient_create: {
        Args: {
          p_cloudevent: Json
          p_cloudevent_id: string
          p_codice_fiscale: string | null // PATCH: nullable in SQL
          p_date_of_birth: string | null // PATCH: nullable in SQL
          p_family_name: string
          p_finalita: string
          p_given_name: string
          p_patient_id: string
          p_sex: string | null // PATCH: nullable in SQL
        }
        Returns: Json
      }
      patient_delete: {
        Args: {
          p_cloudevent: Json
          p_cloudevent_id: string
          p_finalita: string
          p_patient_id: string
        }
        Returns: Json
      }
      patient_update: {
        Args: {
          p_cloudevent: Json
          p_cloudevent_id: string
          p_codice_fiscale: string | null // PATCH: nullable in SQL
          p_date_of_birth: string | null // PATCH: nullable in SQL
          p_family_name: string | null // PATCH: nullable in SQL (partial update)
          p_finalita: string
          p_given_name: string | null // PATCH: nullable in SQL (partial update)
          p_patient_id: string
          p_sex: string | null // PATCH: nullable in SQL
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never
